#=======================================================================
#                       Configuration File
# ---------------------------------------------------------------------
# This file contains all of the user-specified parameters for running 
# the SPARCS pipeline.
#  
# Replace each of the values to the right of the colon for each 
# parameters with the appropriate value.
# 
#   ---- Note: File paths must be absolute file paths! ----
#=======================================================================

# -- PATHS -- #
#############################################################
# Working_directory - directory to store the output folders  
#############################################################
working_directory: /storage/home/kjk6173/scratch/sparcs_test

# -- INPUT FILES -- # 
#############################################################
# vcf_file - Variants file 
#############################################################
vcf_file: /storage/home/kjk6173/work/yeast_data/saccharomyces_cerevisiae.1000.vcf

#############################################################
# gtf_file - Gene model (must be in GTF format)
#############################################################
gtf_file: /storage/home/kjk6173/work/yeast_data/Saccharomyces_cerevisiae.R64-1-1.55.gtf

#############################################################
# ref_genome - Reference genome in FASTA format 
#############################################################
ref_genome: /storage/home/kjk6173/work/yeast_data/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa 


# -- PARAMETERS -- #
#############################################################
# Name - File prefix name 
#############################################################
name: test

#############################################################
# out_name - Name of the output directory
#############################################################
out_name: test

#############################################################
# flank_length - number of nucleotides on either side of 
#                the SNP for riboSNitch prediction
#############################################################
flank_len: 50

#############################################################
# Chunks - The number of splits of the input files 
#############################################################
chunks: 1

#############################################################
# temperature - Temperature for RNA folding
#############################################################
temperature: 37.0

#############################################################
# temp_step - Temperature step for RNA folding
#############################################################
temp_step: 5

#############################################################
# ribosnitch_prediction_tool: Tool to use for predicting
#                             riboSNitches 
#                            (SNPfold or RipRap)  
#############################################################
ribosnitch_prediction_tool: RipRap

#############################################################
# structure_prediction_tool: Tool to use for predicting the RNA
#                  structural ensembles (RNAfold or RNAstructure)
#############################################################
structure_prediction_tool: RNAstructure



# -- ADVANCED PARAMETERS -- #
#############################################################
# riprap_min_window: Minimum window size for RipRap
#############################################################
riprap_min_window: 3

scramble: FALSE